pipeline:
  name: lambda pipeline
  identifier: lambdacicd
  projectIdentifier: lambda
  orgIdentifier: default
  tags: {}
  properties:
    ci:
      codebase:
        connectorRef: githup-harness
        repoName: aws-lambda-demo
        build:
          type: branch
          spec:
            branch: harness
  stages:
    - stage:
        name: Build_and_Package
        identifier: Build_and_Package
        type: CI
        spec:
          cloneCodebase: true
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
          execution:
            steps:
              - step:
                  type: Run
                  name: Zip Files
                  identifier: Zip_Files
                  spec:
                    shell: Sh
                    command: |
                      # Zip the AWS Lambda function code
                      zip -r function.zip .
              - step:
                  type: S3Upload
                  name: Upload Zip to S3
                  identifier: Upload_Zip_to_S3
                  spec:
                    connectorRef: AWS_S3
                    region: us-east-1
                    bucket: YOUR_S3_BUCKET
                    sourcePath: function.zip
                    target: <+pipeline.name>/<+pipeline.sequenceId>
    - stage:
        name: Deploy_Lambda
        identifier: Deploy_Lambda
        type: CI
        spec:
          cloneCodebase: false
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
          execution:
            steps:
              - step:
                  type: Run
                  name: Deploy Lambda
                  identifier: Deploy_Lambda
                  spec:
                    connectorRef: dockerhub
                    image: amazon/aws-cli:2
                    shell: Sh
                    command: |
                      # Download the zip from S3
                      aws s3 cp s3://YOUR_S3_BUCKET/<+pipeline.name>/<+pipeline.sequenceId>/function.zip function.zip
                      # Update the AWS Lambda function code
                      aws lambda update-function-code --function-name YOUR_LAMBDA_FUNCTION_NAME --zip-file fileb://function.zip --region us-east-1
                    environmentVariables:
                      - name: AWS_ACCESS_KEY_ID
                        type: Secret
                        value: <+secrets.getValue("ACCESS_KEY_ID")>
                      - name: AWS_SECRET_ACCESS_KEY
                        type: Secret
                        value: <+secrets.getValue("SECRET_ACCESS_KEY")>
